[package]
name = "pimu"
version = "0.1.0"
authors = ["James Hinshelwood <jadh2@cam.ac.uk>"]
edition = "2018"
build = "build.rs"

[dependencies]
moniker = "0.5.0"
lalrpop-util = "0.17.0"
regex = "1.1.6"
lazy_static = "1.3.0"

[build-dependencies]
lalrpop = "0.16.3"
